/// <reference types="bun" />

import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { getEngineStatus } from "../src/db/engine-data";
import { getBriefingCardById, getBriefingCards } from "../src/db/briefing";

/**
 * Cross-language contract check. engine/tests/test_integration.py builds a bundle from
 * the REAL TradingAgents pydantic schemas (delta-extended) and writes it here; this
 * test validates that same file against the dashboard's zod ingestion schema and the
 * briefing surface — proving a real-schema-derived bundle round-trips end to end.
 *
 * The fixture is generated by the Python engine venv; if it is absent (engine venv not
 * set up in this environment) the check is skipped rather than failing spuriously.
 */
const DIR = join(process.cwd(), "tests", "fixtures", "engine-integration");
const present = existsSync(DIR) && existsSync(join(DIR, "engine-run-2026-06-03.json"));

describe("engine integration bundle validates against the zod contract", () => {
  test.if(present)(
    "a bundle built from real TradingAgents schemas passes zod ingestion + renders",
    () => {
      const prev = process.env.ENGINE_OUT_DIR;
      process.env.ENGINE_OUT_DIR = DIR;
      try {
        const status = getEngineStatus();
        expect(status.state).toBe("live"); // zod-valid + not future-stamped
        if (status.state !== "live") return;

        // Buy rating mapped to a high conviction by the real schema -> adapter path.
        const cards = getBriefingCards();
        expect(cards.length).toBe(1);
        expect(cards[0].provenance.label).toBe("Engine output");
        expect(cards[0].conviction).toBeGreaterThanOrEqual(8);

        // Every ingested artifact carries bitemporal stamps.
        expect(cards.every((c) => c.event_time && c.knowledge_time)).toBe(true);

        // The PM-generated falsification condition (added schema field) survives to the journal.
        const detail = getBriefingCardById(cards[0].id);
        expect(detail?.drivers.length).toBeGreaterThanOrEqual(2);
        expect(detail?.decision_journal_entry?.falsification_condition).toContain("Data-center");
      } finally {
        if (prev === undefined) delete process.env.ENGINE_OUT_DIR;
        else process.env.ENGINE_OUT_DIR = prev;
      }
    },
  );

  test("contract fixture presence is recorded", () => {
    // Always-on assertion so the suite reports whether the cross-language check ran.
    expect(typeof present).toBe("boolean");
  });
});
